### ISSUE TITLE
compatible with Kodi v17

### ISSUE THREAD

**Issue by sveni-lee** [lufinkey/kodi-openbox#1]
I tried to use it with Kodi v17 Beta 3 but I don't get it work.
always boot into openbox and Kodi never starts...

**Comment by lufinkey** [comment]
I'll check this out when I get the chance. Did you make sure to set the session to "kodi openbox", rather than just openbox?

**Comment by sveni-lee** [comment]
where could I check this?
here is a error:

> openConnection: connect: Datei oder Verzeichnis nicht gefunden
> cannot connect to brltty at :0
> /usr/bin/kodi-openbox-session: Zeile 74: /usr/lib/kodi/kodi.bin: Datei oder Verzeichnis nicht 
> 
> gefunden

**Comment by lufinkey** [comment]
Well how are you starting kodi-openbox?

If you're in ubuntu, you need to select the kodi openbox session at the [login screen](http://i.stack.imgur.com/lFmMj.png)

**Comment by sveni-lee** [comment]
I have changed the /etc/lightdm/lightdm.conf

`[Seat:*]
autologin-user=[USER]
autologin-session=kodi-openbox`

**Comment by sveni-lee** [comment]
i don't wnt to close... Im not so familar with github

**Comment by lufinkey** [comment]
after changing the autologin session, try rebooting and it should boot into kodi-openbox

**Comment by sveni-lee** [comment]
it always boots into openbox with the same error...

**Comment by lufinkey** [comment]
Do you have kodi installed? It says it can't find kodi

**Comment by sveni-lee** [comment]
it says it can't find kodi.bin... may I should try with /usr/bin/kodi

open comandline in openbox and type kodi... starts kodi

**Comment by lufinkey** [comment]
thats weird. kodi.bin should be at that path. Hm. I'll look into this. What OS are you running this on, and is it 32 bit or 64 bit?

**Comment by sveni-lee** [comment]
64bit Ubuntu 16.04.1

**Comment by lufinkey** [comment]
That's exactly what I have. How did you install kodi? And how did you install kodi-openbox?

**Comment by sveni-lee** [comment]
installed kodi ppa unstable and kodi openbox from your github

change the kodi.openbox.session  to /usr/bin/kodi in line 74 solved the problem for now...

**Comment by lufinkey** [comment]
alright well that's good. I'll look into the issue

**Comment by sveni-lee** [comment]
Next little thing is, that after Hybernat it boot into LightDM login screen...
I'm not sure if it's related to your script...

**Comment by lufinkey** [comment]
That's a setting you'll have to change yourself. It doesn't have to do with
my script

**Comment by sveni-lee** [comment]
Okay... I thought so... thanks

**Comment by lufinkey** [comment]
This issue should be fixed in the latest release
