### ISSUE TITLE
Add postinst to DEBIAN

### ISSUE THREAD

**Issue by solbero** [lufinkey/kodi-openbox#2]
There is no included postinst included in the DEBIAN folder. This results in that the files installed by the .deb created by install.sh retain the ownership of the user that created the .deb. All files installed to /usr/bin/ are owned by this user instead of root.

**Comment by solbero** [comment]
Well, this is silly of me. I have used a lot of Linux, but I haven’t really dabbled in packaging. It seems like I just forgot to set the ownership of the folder `kodi-openbox` and its contents to `root` before packaging. Makes sense since the files are installed to the root file system.

**Comment by lufinkey** [comment]
ah I see what you mean. I'll fix this

**Comment by lufinkey** [comment]
issue is fixed. just install "fakeroot", rebuild the debian package, and install it.
